### PR TITLE
fix: manufacture items label

### LINKED ISSUE #191: [mobile] Add planned start date and work order number to "Manufacture" ListView

### PR DESCRIPTION
**Pull request by lauty95**
Change label to have a format `order - WO` and added a start date as description
Captura de pantalla 2024-10-03 a la(s) 3 03 15 p  m

> I made a `yarn build` and yarn.lock has changed. Is it ok?

### CODE REVIEW

**Comment by agritheory** [comment]
@lauty95 Changing the yarn lock file is fine.

File: beam/www/beam/pages/Manufacture.vue [hunk 1]
```diff
@@ -19,14 +19,16 @@ const store = useDataStore()
...
 		order_by: 'creation asc',
 	})
 
 	orders.forEach(row => {
+		const order = row.name?.split("-").pop()
 		items.value.push({
 			...row,
-			label: row.item_name,
+			label: `${order} - ${row.item_name}`,
+			description: row.planned_start_date.split(" ")[0],
```
Comment (agritheory) [inline beam/www/beam/pages/Manufacture.vue]: Let's use a `Date` abstraction here instead of trusting the format that's being returned from the API.

**Review by agritheory — CHANGES_REQUESTED** [review]
